baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Juan Juan Zero'
theme = 'juanTrickPony'

[menu]
  [[menu.main]]
    name = "Home"
    pre = "bi-house-door-fill"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "bi-book-fill"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "bi-tags-fill"
    url = "/tags/"
    weight = 3