languageCode = 'en-us'
title = 'JuanJuanZero'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "bi-house-door-fill"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "bi-book-fill"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    pre = "bi-tags-fill"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    pre = "bi-tags-fill"
    url = "/tags/"
    weight = 4